### ISSUE TITLE
Enable dodgr to create route networks with total values aggregated from variables at the OD level

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/dodgr#31] opened 2017-12-07 13:58 UTC

**Comment by Robinlovelace** [comment] 2017-12-07 14:02
Reprex on its way.

**Comment by Robinlovelace** [comment] 2017-12-07 14:41
``` r
library(stplanr)
library(dodgr)
head(cents_sf)
#> Simple feature collection with 6 features and 4 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: -1.550806 ymin: 53.8041 xmax: -1.511861 ymax: 53.82887
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#>       geo_code  MSOA11NM percent_fem  avslope
#> 1708 E02002384 Leeds 055    0.458721 2.856563
#> 1712 E02002382 Leeds 053    0.438144 2.284782
#> 1805 E02002393 Leeds 064    0.408759 2.361707
#> 1925 E02002367 Leeds 038    0.591141 5.091685
#> 1928 E02002363 Leeds 034    0.525161 3.076791
#> 1930 E02002361 Leeds 032    0.511777 3.589363
#>                            geometry
#> 1708 POINT (-1.54646277949532 53...
#> 1712 POINT (-1.51186137386083 53...
#> 1805 POINT (-1.52420468703814 53...
#> 1925 POINT (-1.55080649003917 53...
#> 1928 POINT (-1.5356167992133 53....
#> 1930 POINT (-1.51673370812915 53...
head(flow[1:3])
#>        Area.of.residence Area.of.workplace All
#> 920573         E02002361         E02002361 109
#> 920575         E02002361         E02002363  38
#> 920578         E02002361         E02002367  10
#> 920582         E02002361         E02002371  44
#> 920587         E02002361         E02002377  34
#> 920591         E02002361         E02002382   7
# od = od2odf(flow = flow[1:3], zones = cents_sf) # nb robin - fix for sf
# objects
l = od2line(flow[1:10, 1:3], cents_sf)
plot(l$geometry)
r = line2route(l, route_fun = route_osrm)
#> Warning in value[[3L]](cond): Fail for line number 1
#> 10 % out of 10 distances calculated
#> 20 % out of 10 distances calculated
#> 30 % out of 10 distances calculated
#> 40 % out of 10 distances calculated
#> 50 % out of 10 distances calculated
#> 60 % out of 10 distances calculated
#> 70 % out of 10 distances calculated
#> 80 % out of 10 distances calculated
#> Warning in value[[3L]](cond): Fail for line number 9
#> 90 % out of 10 distances calculated
#> 100 % out of 10 distances calculated
r$value = 1:nrow(r)

# the result I'm after, but needs very inefficient arg buff_dist to work
rnet = overline(r, attrib = "value")
plot(rnet, lwd = rnet$value, col = "yellow", add = T)
plot(r, add = T, lwd = r$value, col = "blue")
#> Warning in plot.sf(r, add = T, lwd = r$value, col = "blue"): ignoring all
#> but the first attribute
```

![](https://i.imgur.com/Jt2tRM2.png)

``` r

# trying with dodgr: g = weight_streetnet(r) # that should do it but fails
r$highway = "cycleway"
g = weight_streetnet(r)  # still not working
#> Error in weight_streetnet(r): sf_lines must be class "sf" and have highway and geometry columns
rnet_dodgr = dodgr_aggregate(g)  # or something like that
#> Error in dodgr_aggregate(g): could not find function "dodgr_aggregate"

# expected result
plot(rnet_dodgr)
#> Error in plot(rnet_dodgr): object 'rnet_dodgr' not found
```

**Comment by mpadge** [comment] 2018-02-19 18:44
@Robinlovelace Is this now achieved with the (newly split and renamed) `dodgr_flows_aggregate()` and `dodgr_flows_disperse()` functions? Can it be closed?

**Comment by Robinlovelace** [comment] 2018-02-26 15:23
I will check it out now...

**Comment by Robinlovelace** [comment] 2018-02-26 16:07
Looking good but I still cannot see how to reproduce the result of `overline()`. See my attempt to understand what's going on below. The main issues are

- `weight_streetnet()` fails on linestrings with strange error message:

```
Error in rcpp_sf_as_network(sf_lines, pr = wt_profile) : 
  sf_lines have no geometry component
```

- The plots at the end don't seem to generate a coherent aggregated network though the study area (may be an issue of point locations) - below is printed the final map I get out (reprex not working on this but it is reproducible)

```r
library(stplanr)
library(dodgr)
l = od2line(flow[2:4, 1:3], cents_sf)
mapview::mapview(l$geometry)
r = line2route(l, route_fun = route_osrm)
r$value = 1:nrow(r)
rnet = overline(r, attrib = "value")
plot(rnet, lwd = rnet$value, col = "yellow", add = T)
plot(r$geometry, add = T, lwd = r$value, col = "blue")

# trying with dodgr: g = weight_streetnet(r) # that should do it but fails
r$highway = "cycleway"
library(sf)
g = weight_streetnet(r)  # still not working
r2 = dodgr_streetnet("Chapel Allerton, Leeds")
g = weight_streetnet(r2)
flows_agg = dodgr_flows_aggregate(g, from = st_coordinates(cents_sf[1:3, ]), to = st_coordinates(cents_sf[4:7, ]), flows = 1:3)  # or something like that
summary(flows_agg$flow)
rnet_dodgr = dodgr::dodgr_to_sf(flows_agg)
# expected result
plot(rnet_dodgr, lwd = flows_agg$flow, col = "red")

flows_dis = dodgr_flows_disperse(graph = g, from = st_coordinates(cents_sf[1:3, ]), dens = 1:3)
summary(flows_dis)
rnet_dodgr_dis = dodgr_to_sf(flows_dis)
plot(rnet_dodgr_dis, col = "yellow", lwd = flows_dis$flow, add = TRUE)
plot(rnet_dodgr, add = TRUE)

```

**Comment by mpadge** [comment] 2018-02-26 19:04
Cool, thanks fur the reprex.. I'll have a play with it asap

**Comment by mpadge** [comment] 2018-03-05 12:35
The above commit permits the following code. First your `stplanr` way:
```
library (dodgr)
library(stplanr)
l = od2line(flow[1:10, 1:3], cents_sf)
r = line2route(l, route_fun = route_osrm)
r$value = 1:nrow(r)
rnet = overline(r, attrib = "value")
x11 ()
par (mfrow = c (1, 2))
plot(l$geometry)
plot(rnet, lwd = rnet$value, col = "yellow", add = T)
plot(r, add = T, lwd = r$value, col = "blue")
```
Then the new `dodgr` code added in that commit, which primarily implements the `keep_cols` argument:
```
g = weight_streetnet(r, wt_profile = 1, keep_cols = "value")
rnet_dodgr = dodgr_flows_aggregate (g, flows = g$value)
dodgr_flowmap (rnet_dodgr, linescale = 10)
```
![junk](https://user-images.githubusercontent.com/6697851/36971697-f2b42d3c-206c-11e8-91e1-03a2cd14db44.png)

Note how much more detailed the `dodgr` results are:
```
> length(unique(rnet_dodgr$flow)
# 354
> length(unique(r$value))
# 10
```
Different flows are accumulated on every single segment of the network, instead of just lumping them into the 10 `sf` geometries. This reveals what `dodgr` actually does in this case. `dodgr` treats flows as a strictly point-source phenomenon, whereas `stplanr` uses the entire lines as sources. Thus specifying each `LINESTRING` object as a source in `dodgr` means that every single node in that linestring is an independent source, and thus flows accumulate along the length of that line. This is an appropriate approach, and reflects universal practice throughout most domains of modern physics. Flows are aggregated from point sources, not from abstract sources of finite extent. This means that `dodgr` will aggregate different flow levels even when only a single `sf::LINESTRING` object is specified as the source.

## Translation into `stplanr::overline`

The above code still relies on `stplanr::line2route` to generate the actual network. A full `dodgr` replacement would also require a replacement for the functionality of `stplanr::overline()`. The first thing this would require would be more precise specification of what is being aggregated, most importantly precise specification of point, rather than line, sources. Having specified those, aggregation would be pretty easy. Let's pretend the points are simply the mean coordinates of each `LINESTRING` object:
```
pts <- lapply (l$geometry, function (i) colMeans (i)) %>% do.call (rbind, .)
```
We then need to construct a `dodgr` flow matrix from the structure of `l` (these lines are more efficient than any `tidyverse` approach):
```
indx <- match (paste0 (l$Area.of.residence, l$Area.of.workplace),
               paste0 (flow$Area.of.residence, flow$Area.of.workplace))
nfr <- unique (l$Area.of.residence [1:10])
nto <- unique (l$Area.of.workplace [1:10])
fmat <- array (NA, dim = c (length (nfr), length (nto)))
fmat [nfr == l$Area.of.residence & nto == l$Area.of.workplace] <- l$All [indx]
```
Then get the street network via `osmdata`, and match `pts` to OSM vertex IDs:
```
net <- dodgr_streetnet (pts = st_coordinates (l), expand = 0.2) %>%
    weight_streetnet (wt_profile = "bicycle") # or whatever
ids <- match_pts_to_graph (dodgr_vertices (net), pts)
```
Then off we go the `dodgr` way:
```
indx1 <- match (nfr, l$Area.of.residence [1:10])
indx2 <- match (nto, l$Area.of.workplace [1:10])
net <- dodgr_flows_aggregate (net, from = ids [indx1], to = ids [indx2],
                            flow = fmat)
dodgr_flowmap (net, linescale = 10)
```
![junk](https://user-images.githubusercontent.com/6697851/36974686-cb6ad5a4-2077-11e8-8bbd-78ed359dbaa1.png)

The result has enormously more detail, and includes many more routes other than just the direct connections between the routing points.

## Reproducible code + timing

The following timings analyses all possible flows from the `stplanr::flow` data, not just `[1:10]`, as analysed above.
```
library (dodgr) # latest version
library(stplanr)
library(sf)
l = od2line(flow[, 1:3], cents_sf) # ALL data!
net <- dodgr_streetnet (pts = st_coordinates (l), expand = 0.2) %>%
    weight_streetnet (wt_profile = "bicycle") # or whatever

stp <- function (l)
{
    r = line2route(l, route_fun = route_osrm)
    r$value = 1:nrow(r)
    overline(r, attrib = "value")
}
dodge <- function (l, streetnet)
{
    pts <- lapply (l$geometry, function (i) colMeans (i)) %>%
        do.call (rbind, .)

    nfr <- unique (l$Area.of.residence)
    nto <- unique (l$Area.of.workplace)
    fmat <- array (NA, dim = c (length (nfr), length (nto)))
    rownames (fmat) <- nfr
    colnames (fmat) <- nto
    indx1 <- match (l$Area.of.residence, nfr)
    indx2 <- match (l$Area.of.workplace, nto)
    fmat [(indx2 - 1) * nrow (fmat) + indx1] <- l$All

    verts <- dodgr_vertices (streetnet)
    ids <- verts$id [match_pts_to_graph (verts, pts)]
    dodgr_flows_aggregate (streetnet, from = ids [indx1], to = ids [indx2],
                           flows = fmat)
}
rbenchmark::benchmark (g1 <- stp (l),
                       g2 <- dodge (l, net),
                       replications = 2)$relative
```
`dodgr` is around 50 times faster than the `line2route %>% overline` pipe. (Also scales much better, so even faster for bigger tasks.) I've no idea at the mo which bits of this might best be bundled as distinct functions? @Robinlovelace Please advise!

-----------------------------------

# Masters of the (R Spatial) Universe and `silicate`

@mdsumner: Don't worry about too much detail of the above, but what it does is pretty neatly (imho) implement the necessary missing steps for the `silicate` workflow
```
(generic input ->) `sf` -> `silicate` -> `sf` -> (generic output)
```
keeping full record of all `sf` feature IDs along the way, and so enabling final generic output to be mapped back to the initial `sf` input structure. This is now ready for incorporation into `silicate`, which I'll aim to do this week.
```

**Comment by Robinlovelace** [comment] 2018-03-05 14:10
Wow that is a pretty comprehensive bug fix that goes beyond the functionality in `overline()`. I still think it would be useful to have a setting that allows the result to be the same as the `overline()` result, e.g. as described here (1721 should objectively be the correct value for the final line in another reproducible example: https://gis.stackexchange.com/questions/139681/overlaying-lines-and-aggregating-their-values-for-overlapping-segments ).

No time to test this but looks like impressive progress.

**Comment by Robinlovelace** [comment] 2018-03-05 14:13
BTW that final plot in your answer above does not look intuitively right compared with the straight line ODs it aggregates.

**Comment by mpadge** [comment] 2018-03-05 21:01
That last plot was a bosh job from made-up coordinates taken as mid-points of the lines. Then i realised the actual coordinates were all in `stplanr::cents_sf`, so real code that directly compares the 2 approaches looks like this:
```
library(dodgr)
library(stplanr)
library(sf)

#  route via stplanr:
l = od2line(flow[1:10, 1:3], cents_sf)
r = line2route(l, route_fun = route_osrm)
r$value = 1:nrow(r)
rnet = overline(r, attrib = "value")
r$highway = "cycleway"
g = weight_streetnet(r, keep_cols = "value")
rnet_dodgr = dodgr_flows_aggregate (g, flows = g$value) %>%
    merge_directed_flows ()
par (mfrow=c(1,2))
dodgr_flowmap (rnet_dodgr, linescale = 10)
points (pts, pch = 19, cex = 3, col = "blue")

# route via dodgr:
pts <- st_coordinates (cents_sf$geometry)
fmat <- array (NA, dim = rep (nrow (pts), 2))
indx1 <- match (flow$Area.of.residence, cents_sf$geo_code)
indx2 <- match (flow$Area.of.workplace, cents_sf$geo_code)
fmat [(indx2 - 1) * nrow (fmat) + indx1] <- flow$All

# Get street network via `osmdata`
net <- dodgr_streetnet (pts = pts, expand = 0.2) %>%
    weight_streetnet (wt_profile = "bicycle") # or whatever
verts <- dodgr_vertices (net)
ids <- verts$id [match_pts_to_graph (verts, pts)]
g <- dodgr_flows_aggregate (net, from = ids, to = ids, flows = fmat) %>%
    merge_directed_flows ()

dodgr_flowmap (g, linescale = 10)
points (pts, pch = 19, cex = 3, col = "blue")
```
![junk](https://user-images.githubusercontent.com/6697851/36999343-1ad33526-20c0-11e8-84e0-e2cbe1a6ad65.png)

Concentrating for example on flows between the southern- and easternmost points reveals that the `stplanr` code sends those flows first way up north before curving back down south to reach the easternmost point. The `dodgr` code flows through several paths, including two that are definitely more direct. `dodgr` simply returns far more paths than the `stplanr` code, which only routes through a network of 10 items in total (that is, shortest paths are routed through aggregated linestring objects, meaning they can not branch off at any point along those lines).

**Comment by mpadge** [comment] 2018-03-05 21:41
Finally, some code to check it out yourself via `mapview` (also exercise for me in `sf`-ification of it all)
```
library(dodgr)
library(stplanr)
library(sf)
pts <- st_coordinates (cents_sf$geometry)
fmat <- array (NA, dim = rep (nrow (pts), 2))
indx1 <- match (flow$Area.of.residence, cents_sf$geo_code)
indx2 <- match (flow$Area.of.workplace, cents_sf$geo_code)
fmat [(indx2 - 1) * nrow (fmat) + indx1] <- flow$All
net <- dodgr_streetnet (pts = pts, expand = 0.2) %>%
    weight_streetnet (wt_profile = "bicycle") # or whatever
verts <- dodgr_vertices (net)
ids <- verts$id [match_pts_to_graph (verts, pts)]
g <- dodgr_flows_aggregate (net, from = ids, to = ids, flows = fmat) 
geoms <- dodgr_to_sf (g)
gc <- dodgr_contract_graph (g)
gsf <- st_sf (geoms)
gsf$flow <- gc$graph$flow
gsf <- gsf [which (gsf$flow > 0), ]
flow <- gsf$flow / max (gsf$flow)
ncols <- 30
cols <- colorRampPalette (c ("lawngreen", "red")) (ncols) [ceiling (ncols * flow)]
library (mapview)
m <- mapview (gsf, color = cols, lwd = 10 * flow)
addFeatures (m, cents_sf)
```
Note only that those flows are not yet merged, so they are still directed, meaning if edge A is repeated in reverse order later in the graph, then only the latter will appear, and will overwrite the former. I'll open an issue to fix that. Otherwise I think the results look really good.

**Closed** 2018-10-25 08:55 UTC
Labels: bug

**Comment by mpadge** [comment] 2018-10-25 08:57
@Robinlovelace Let me know if there are any remaining issues here. I had a look through to see whether there was anything that might be incorporated into new functions, but I think it's essentially just the core of `dodgr_flows_aggregate`. I'd say what we need to do is sit down in person one day and just nut out the overlap and potential convergence between `dodgr_flows_aggregate` and `stplanr::overline()`.

**Comment by Robinlovelace** [comment] 2018-10-25 10:36
> I'd say what we need to do is sit down in person one day and just nut out the overlap and potential convergence between dodgr_flows_aggregate and stplanr::overline().

Fully agreed. One for December? Awesome work on this that is important for transport planning software (a la FTMOD proposal) - overline is still one of the components of **stplanr** in need of a decent overhaul and re-implementing it using this code will be of huge benefit. Thank you!
