### ISSUE TITLE
Issue running hampi example

### ISSUE THREAD

**Issue by douglascm** [ATFutures/dodgr#126] opened 2020-01-12 21:10 UTC
``` r
library(dodgr)
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- sample (v$id, size = 20)
to <- sample (v$id, size = 50)
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (runif (length (from) * length (to)), dim = c (length (from), length (to)))
length (from); length (to); dim (flows)
#> [1] 20
#> [1] 50
#> [1] 20 50
#> [1] 20
#> [1] 50
#> [1] 20 50
f <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
sum(f$flow)
#> [1] 0
```

<sup>Created on 2020-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I try to run the following code and this is the result, used to work back when i was using version 0.2.0, newer versions will not output correct value, I tried installing older versions with:
install_version("dodgr", version = "0.2.0", repos = "http://cran.us.r-project.org")
But I get a RcppParallel compilation related error:

`1/R/R-36~1.2/bin/i386 -lRlapack -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lRblas -lgfortran -lm -lquadmath -LD:/First Last/Documents/R/win-library/3.6/RcppParallel/lib/i386 -ltbb -ltbbmalloc -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lR
g++.exe: error: Last/Documents/R/win-library/3.6/RcppParallel/lib/i386: No such file or directory
no DLL was created`

**Comment by douglascm** [comment] 2020-01-12 21:33
Already tried removing R and all packages and installing again. My OS is windows

**Comment by douglascm** [comment] 2020-01-13 01:29
Just tried in a friend's computer that never had any R on it, still get 0. Both windows.

**Comment by douglascm** [comment] 2020-01-13 14:21
It works on MacOS.

**Comment by mpadge** [comment] 2020-01-13 16:41
Please run this reprex, which should be *exactly* reproducible because there are no random values involved:
``` r
library(dodgr)
sessionInfo()
#> R version 3.6.2 (2019-12-12)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Arch Linux
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/libblas.so.3.9.0
#> LAPACK: /usr/lib/liblapack.so.3.9.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
#>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
#>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dodgr_0.2.5.030 testthat_2.3.1  nvimcom_0.9-71 
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3         pillar_1.4.3       compiler_3.6.2     highr_0.8         
#>  [5] prettyunits_1.1.0  remotes_2.1.0      tools_3.6.2        digest_0.6.23     
#>  [9] pkgbuild_1.0.6     pkgload_1.0.2      tibble_2.1.3       lubridate_1.7.4   
#> [13] jsonlite_1.6       lattice_0.20-38    evaluate_0.14      memoise_1.1.0     
#> [17] pkgconfig_2.0.3    rlang_0.4.2        cli_2.0.1          rstudioapi_0.10   
#> [21] curl_4.3           yaml_2.2.0         xfun_0.11          xml2_1.2.2        
#> [25] httr_1.4.1         withr_2.1.2        stringr_1.4.0      knitr_1.26        
#> [29] desc_1.2.0         fs_1.3.1           devtools_2.2.1     grid_3.6.2        
#> [33] rprojroot_1.3-2    glue_1.3.1         R6_2.4.1           processx_3.4.1    
#> [37] fansi_0.4.1        rmarkdown_2.0      sessioninfo_1.1.1  sp_1.3-2          
#> [41] osmdata_0.1.2      callr_3.4.0        magrittr_1.5       backports_1.1.5   
#> [45] ps_1.3.0           ellipsis_0.3.0     htmltools_0.4.0    usethis_1.5.1     
#> [49] RcppThread_0.5.4   rvest_0.3.5        assertthat_0.2.1   stringi_1.4.4     
#> [53] RcppParallel_4.4.4 crayon_1.3.4
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- v$id [1:20]
to <- v$id [1:50]
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (1, dim = c (length (from), length (to)))
f <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
sum(f$flow)
#> [1] 980
summary(f$flow)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>  0.0000  0.0000  0.0000  0.1641  0.0000 16.1459
```

<sup>Created on 2020-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Your error in trying to install previous versions of `dodgr` looks like a corruption in your `RcppParallel` installation. You really should *not* need to resort to installing previous versions of `dodgr`, because i do not think this package can be the cause of your result which i can not reproduce, but if you really want, then that would seem to suggest that you first uninstall and reinstall `RcppParallel`, and also uninstall `dodgr` before trying to install previous versions.

**Comment by mem48** [comment] 2020-01-14 13:47
I'm getting the same problem on Windows

library(dodgr)
#> Warning: package 'dodgr' was built under R version 3.6.1
sessionInfo()
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17763)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United Kingdom.1252 
#> [2] LC_CTYPE=English_United Kingdom.1252   
#> [3] LC_MONETARY=English_United Kingdom.1252
#> [4] LC_NUMERIC=C                           
#> [5] LC_TIME=English_United Kingdom.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dodgr_0.2.5
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3         osmdata_0.1.1      knitr_1.26         xml2_1.2.2        
#>  [5] magrittr_1.5       rvest_0.3.5        lattice_0.20-38    R6_2.4.1          
#>  [9] rlang_0.4.2        stringr_1.4.0      highr_0.8          httr_1.4.1        
#> [13] tools_3.6.0        grid_3.6.0         xfun_0.11          htmltools_0.4.0   
#> [17] yaml_2.2.0         RcppParallel_4.4.4 digest_0.6.23      tibble_2.1.3      
#> [21] crayon_1.3.4       curl_4.3           evaluate_0.14      rmarkdown_1.18    
#> [25] sp_1.3-2           stringi_1.4.3      compiler_3.6.0     pillar_1.4.2      
#> [29] jsonlite_1.6       lubridate_1.7.4    pkgconfig_2.0.3
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- v$id [1:20]
to <- v$id [1:50]
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (1, dim = c (length (from), length (to)))
f <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
sum(f$flow)
#> [1] 0
summary(f$flow)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>       0       0       0       0       0       0

**Comment by mem48** [comment] 2020-01-14 13:48
This used to work, becuase I'm getting the problem trying to rerun some old code

**Comment by mem48** [comment] 2020-01-14 13:53
Does work on my Linux machine
```
library(dodgr)
sessionInfo()
#> R version 3.6.2 (2019-12-12)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Linux Mint 19.3
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
#> 
#> locale:
#>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
#>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
#>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dodgr_0.2.5
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3         osmdata_0.1.2      knitr_1.26         xml2_1.2.2        
#>  [5] magrittr_1.5       rvest_0.3.5        lattice_0.20-38    R6_2.4.1          
#>  [9] rlang_0.4.2        stringr_1.4.0      highr_0.8          httr_1.4.1        
#> [13] tools_3.6.2        grid_3.6.2         xfun_0.11          htmltools_0.4.0   
#> [17] yaml_2.2.0         RcppParallel_4.4.4 digest_0.6.23      tibble_2.1.3      
#> [21] crayon_1.3.4       curl_4.3           evaluate_0.14      rmarkdown_2.0     
#> [25] sp_1.3-2           stringi_1.4.3      compiler_3.6.2     pillar_1.4.3      
#> [29] jsonlite_1.6       lubridate_1.7.4    pkgconfig_2.0.3
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- v$id [1:20]
to <- v$id [1:50]
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (1, dim = c (length (from), length (to)))
f <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
sum(f$flow)
#> [1] 99300
summary(f$flow)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>    0.00    0.00    0.00   16.62    0.00  520.00
```
Created on 2020-01-14 by the reprex package (v0.3.0)

**Comment by mpadge** [comment] 2020-01-14 14:46
Thanks for confirmation @mem48. I'll try to track down a Windows machine to investigate further, but good to at least learn that it is OS-specific

**Comment by mpadge** [comment] 2020-01-15 04:23
Update after i found an idle windoze machine:
``` r
library(dodgr)
sessionInfo()
#> R version 3.6.2 (2019-12-12)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17763)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] dodgr_0.2.5.030
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.3         osmdata_0.1.2      knitr_1.26         xml2_1.2.2        
#>  [5] magrittr_1.5       rvest_0.3.5        lattice_0.20-38    R6_2.4.1          
#>  [9] rlang_0.4.2        stringr_1.4.0      highr_0.8          httr_1.4.1        
#> [13] tools_3.6.2        grid_3.6.2         xfun_0.12          htmltools_0.4.0   
#> [17] yaml_2.2.0         RcppParallel_4.4.4 digest_0.6.23      tibble_2.1.3      
#> [21] crayon_1.3.4       curl_4.3           evaluate_0.14      rmarkdown_2.0     
#> [25] sp_1.3-2           stringi_1.4.4      compiler_3.6.2     pillar_1.4.3      
#> [29] jsonlite_1.6       lubridate_1.7.4    pkgconfig_2.0.3

graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- sample (v$id, size = 20)
to <- sample (v$id, size = 50)
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (runif (length (from) * length (to)), dim = c (length (from), length (to)))
f <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
message (sum(f$flow))
#> 287.552618893096
```

<sup>Created on 2020-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It all works for me, which is a bit unfortunate here because it prevents me from being able to help any further. One of the few ideas I might suggest would be to first run `dodgr_cache_off()` prior to any of the above lines to see if that makes any difference?

**Comment by mem48** [comment] 2020-01-15 14:52
I tried the `dodgr_cache_off()` and it made no difference, I can't see any significant differences in the `sessionInfo()` this is a bit of a mystery is there a way to get some more detailed messages out of the functions?

**Comment by mpadge** [comment] 2020-01-15 15:07
One strange thing I see is that one listed `Imports` is `callr`, and this is listed in `loaded via namespace` on linux, but not on windows. I do not understand why that would not be listed, but neither was it on the above windows check I did, and  yet it returned results. 

Other than that, the only digging in that can be done from the R side is to run the following code, which is the internals of what the function is doing:
``` r
library (dodgr)
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- v$id [1:20]
to <- v$id [1:50]
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (1, dim = c (length (from), length (to)))
g <- dodgr:::prepare_graph (graph, from, to)
norm_sums <- TRUE
tol <- 1e-12
heap <- "BHeap"
flow <- dodgr:::rcpp_flows_aggregate_par (g$graph, g$vert_map,
                                          g$from_index, g$to_index,
                                          flows, norm_sums, tol, heap)
sum (flow)
#> [1] 980
```

<sup>Created on 2020-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But I imagine in your case that's just going return a vector of zeros? The only potential problem going in to that could be the structure of the `g` object, so you could check that to ensure there are no `NA` values or anything like that?

**Comment by mem48** [comment] 2020-01-15 15:22
I get

```
> g <- dodgr:::prepare_graph (graph, from, to)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'prepare_graph' not found
```

**Comment by mpadge** [comment] 2020-01-15 15:24
Then try cloning the repo locally and doing,
``` r
devtools::load_all (".", export_all = TRUE)
```
and just calling
``` r
g <- prepare_graph (graph, from, to)
```

The relevant difference between `dodgr` 2.4 -> 2.5 is likely to be the default parallelisation of flow aggregation. My guess is that this might be related to some kind of configuration error in the use of the [Thread Building Blocks (TBB) library for windows](http://rcppcore.github.io/RcppParallel/#r_packages)?

> Note that the Windows variation (Makevars.win) requires an extra PKG_CXXFLAGS entry that enables the use of TBB. This is because TBB is not used by default on Windows (for backward compatibility with a previous version of RcppParallel which lacked support for TBB on Windows).

Can you check the equivalent output from `dodgr_dists()`? If those are non-zero, then TBB is obviously working, and so the mystery deepens further

**Comment by mem48** [comment] 2020-01-15 15:53
So first I got,

```
> devtools::load_all (".", export_all = TRUE)
Loading dodgr
Re-compiling dodgr
   ERROR: dependency 'RcppThread' is not available for package 'dodgr'
```
So I installed RcppThread, then `g <- prepare_graph (graph, from, to)` worked and

```
flow <- dodgr:::rcpp_flows_aggregate_par (g$graph, g$vert_map,
                                          g$from_index, g$to_index,
                                          flows, norm_sums, tol, heap)
sum (flow)
[1] 980
```
I then retried the normal method in a different R session but still failed. `dodgr_dists` seems to be working.

```
f2 <- dodgr_dists(graph = graph, from = from, to = to)
> head(f2)
           3921523908 339062241 1376768745 1376769189 3921512071 1376768873 339574171 2627428638
977478668          NA  657.3511  1451.1139   3325.687         NA   3712.268  1745.375         NA
2398957698         NA 4991.8872  4028.7486   4629.187         NA   4374.925  5337.616         NA
1376768896         NA 1753.7518   375.2765   2063.669         NA   3310.489  1856.024         NA
2588146098         NA 3173.2050  2800.2053   4918.236         NA   1618.342  2654.108         NA
286632902          NA  626.9864   781.2538   2655.827         NA   2757.429  1484.681         NA
2717241309         NA 2296.7738  1333.6352   1934.073         NA   3174.209  2642.503         NA

```

**Comment by mpadge** [comment] 2020-01-15 16:02
But by default the only additional line after the above `flow <- ...` is effectively
``` r
graph$flow <- flow
```
and then `graph` is returned. So if it works calling `rcpp_flows_aggregate_par`, then i can't see any way that it can not work when calling `dodgr_flows_aggregate()` directly? Can you please try both in the same session to confirm? (And thanks for digging in to this, i really appreciate it!) And/or, try `devtools::load_all(".", export_all = FALSE)`, and then run `dodgr_flows_aggregate()` directly in that session?

**Comment by mem48** [comment] 2020-01-15 16:07
In the same session that I built the package from source `dodgr_flows_aggregate()` works and give almost the same answer.

```
devtools::load_all (".", export_all = TRUE)
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- v$id [1:20]
to <- v$id [1:50]
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (1, dim = c (length (from), length (to)))
g <- dodgr:::prepare_graph (graph, from, to)
norm_sums <- TRUE
tol <- 1e-12
heap <- "BHeap"
flow <- dodgr:::rcpp_flows_aggregate_par (g$graph, g$vert_map,
                                          g$from_index, g$to_index,
                                          flows, norm_sums, tol, heap)
library(dodgr)
f2 <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
message (sum(f2$flow))
980
summary(flow - f2$flow)
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-3.553e-15  0.000e+00  0.000e+00 -8.740e-19  0.000e+00  1.776e-15 
```

**Comment by mpadge** [comment] 2020-01-15 16:23
At least that's good news! One more thing you could try would then be to remove and reinstall the package from the local repo via:
``` r
remove.packages("dodgr")
devtools::install()
```
If `flows_aggregate` then works with normal `library(dodgr)`, I'd suggest we're all good, and the problem must somehow arise from some `Rtools` thing (or maybe even an issue with the binary source ...?), but if it doesn't work, then ... we'll have to continue digging a bit.

**Comment by mem48** [comment] 2020-01-15 17:15
It works! so we have a partial solution.

**Comment by mpadge** [comment] 2020-01-15 17:35
That's great. @douglascm could you please confirm whether this also works for you? If so, the issue can be closed, because it really does not seem to be *directly* caused by `dodgr` code.

**Comment by douglascm** [comment] 2020-01-15 18:56
> That's great. @douglascm could you please confirm whether this also works for you? If so, the issue can be closed, because it really does not seem to be _directly_ caused by `dodgr` code.

i'll check asap

**Comment by douglascm** [comment] 2020-01-15 19:06
> That's great. @douglascm could you please confirm whether this also works for you? If so, the issue can be closed, because it really does not seem to be _directly_ caused by `dodgr` code.

I'll check as soon as I can, just to clarify I should remove the package, donwload it and install with devtools?

**Comment by mpadge** [comment] 2020-01-15 20:08
That seems to be what worked for @mem48, so yes, please. Or, given that it worked, it would also just as likely work with:
``` r
remove.packages("dodgr")
remotes::install_github("atfutures/dodgr")
```

**Comment by mem48** [comment] 2020-01-15 20:21
@douglascm if this solution works for you I suggest changing the issue title before closing in case others have the same problem.

**Comment by douglascm** [comment] 2020-01-16 02:27
> That seems to be what worked for @mem48, so yes, please. Or, given that it worked, it would also just as likely work with:
> 
> ```r
> remove.packages("dodgr")
> remotes::install_github("atfutures/dodgr")
> ```

Still was getting "g++.exe: error: /Documents/R/win-library/3.6/RcppParallel/lib/i386: No such file or directory no DLL was created". Dodgr wouldnt install from github

Also tried removing and installing RcppParallel and Rcpp with remotes and reinstalling Rtools35.

**Comment by mem48** [comment] 2020-02-11 10:35
@mpadge FYI I'm seeing similar problems with merge_directed_flows on Windows

**Comment by mpadge** [comment] 2020-02-11 12:07
What kind of "similar problems" exactly? Would you care to paste a `reprex`?

**Comment by mem48** [comment] 2020-02-16 23:02
Sorry that was needlessly criptic comment. Looking back I think it is really the same problem in a different guise, that if flow is 0 for all segments then merge directed flows returns a data frame of 0 rows.

On a related note I taught 30 students some dodgr https://github.com/ITSLeeds/TDS/blob/master/practicals/6-routing.md with a seemingly random mix of computers that did or did not have the probem of aggregation

**Comment by mpadge** [comment] 2020-02-17 18:33
ah. that all sounds like good news then. Thanks @mem48 - i recon this issue can be closed now, absent further feedback from @douglascm. Can you pls :+1: if you agree. Thanks as always for input

**Comment by mem48** [comment] 2020-02-17 21:09
Well I still have the problem unless the package is built locally even devtools::install_github() didn't work so there is something not 100% right.

**Closed** 2021-01-27 22:14 UTC
