### ISSUE TITLE
Make weight_streetnet() more likely to succeed (and maybe better documented)

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/dodgr#58] opened 2018-06-08 15:11 UTC
I think there are ways to allow **dodgr** to work more easily - none of this is an 'engineering' problem but a 'user friendliness' issue I think - hope this is makes sense and is useful, an outgrowth of https://github.com/ropensci/stplanr/issues/261

``` r
rnet_decompose <- function(l) {                                                             
if(is.null(l$highway)) l$highway <- "tertiary"                                              
g <- dodgr::weight_streetnet(sf_lines = l, wt_profile = 1)                                  
}                                                                                           
                                                                                            
# testing                                                                                   
library(stplanr)                                                                            
library(dodgr)                                                                              
library(sf)                                                                                 
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
class(hampi)                                                                                
#> [1] "sf"         "data.frame"
hampi # error...                                                                            
#> Error in .subset2(x, i, exact = exact): attempt to select less than one element in get1index
hampi_sf = st_sf(hampi)                                                                     
#> Error in .subset2(x, i, exact = exact): attempt to select less than one element in get1index
# weight_streetnet(hampi) # works                                                           
os_roads_bristol                                                                            
#> Simple feature collection with 29 features and 19 fields
#> geometry type:  LINESTRING
#> dimension:      XY
#> bbox:           xmin: -2.70732 ymin: 51.47842 xmax: -2.616046 ymax: 51.56824
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> # A tibble: 29 x 20
#>    fictitious identifier          class  roadNumber name1 name1_lang name2
#>    <chr>      <chr>               <chr>  <chr>      <chr> <chr>      <chr>
#>  1 false      6E48BDC8-D330-4B26… Motor… M49        <NA>  <NA>       <NA> 
#>  2 false      A2562BED-60E6-4FCF… Motor… M5         <NA>  <NA>       <NA> 
#>  3 false      6DA7405F-E2DA-4052… Motor… M49        <NA>  <NA>       <NA> 
#>  4 false      CB58D923-3EB8-45E4… Motor… M5         <NA>  <NA>       <NA> 
#>  5 false      C9D6EDEB-5227-43F5… Motor… M49        <NA>  <NA>       <NA> 
#>  6 false      41589DA6-0068-4030… Motor… M49        <NA>  <NA>       <NA> 
#>  7 false      E712E6EE-6661-467E… Motor… M5         <NA>  <NA>       <NA> 
#>  8 false      86D187FE-5519-475F… Motor… M49        <NA>  <NA>       <NA> 
#>  9 false      2AB96D1E-CD50-4BAA… Motor… M5         <NA>  <NA>       <NA> 
#> 10 false      E90FDAB3-1F07-431A… Motor… M5         <NA>  <NA>       <NA> 
#> # ... with 19 more rows, and 13 more variables: name2_lang <chr>,
#> #   formOfWay <chr>, length <int>, primary <chr>, trunkRoad <chr>,
#> #   loop <chr>, startNode <chr>, endNode <chr>, structure <chr>,
#> #   nameTOID <chr>, numberTOID <chr>, function. <chr>,
#> #   geometry <LINESTRING [°]>
plot(os_roads_bristol)                                                                      
#> Warning: plotting the first 10 out of 19 attributes; use max.plot = 19 to
#> plot all
```

![](https://i.imgur.com/zpPDt9x.png)

``` r
                                                                                            
# from ?os_roads_open                                                                       
colnm <- "formOfWay" # name of column used to determine weights                             
wts <- c (0.1, 0.2, 0.8, 1)                                                                 
names (wts) <- unique (os_roads_bristol [[colnm]])                                          
os_roads_bristol$highway = "Motorway"                                                       
weight_streetnet(os_roads_bristol) # fails wih unhelpful error msg                          
#> Error in weight_streetnet(os_roads_bristol): sf_lines must be class "sf" and have highway and geometry columns
net <- weight_streetnet (os_roads_bristol, wt_profile = wts, # fails wih unhelpful error msg
type_col = colnm, id_col = "identifier")                                                    
#> Error in rcpp_sf_as_network(sf_lines, pr = wt_profile): sf_lines have no geometry component
os_roads_bristol$highway <- NULL                                                            
net <- weight_streetnet (os_roads_bristol, wt_profile = wts, # works!!!!                    
type_col = colnm, id_col = "identifier")                                                    
# another example...                                                                        
data_dir <- system.file("extdata", package = "stplanr")                                     
unzip(file.path(data_dir, "sydroads.zip"), exdir = tempdir())                               
sydroads <- read_sf(tempdir(), "roads")                                                     
plot(sydroads$geometry)                                                                     
```

![](https://i.imgur.com/nEb0AlS.png)

``` r
names(sydroads)                                                                             
#> [1] "osm_id"   "name"     "ref"      "type"     "oneway"   "bridge"  
#> [7] "maxspeed" "geometry"
colnm <- "type"                                                                             
road_types <- unique (sydroads[[colnm]])                                                    
wts <- rep(1, length(road_types))                                                           
names (wts) <- road_types                                                                   
weight_streetnet(sydroads)  # fails                                                         
#> Error in weight_streetnet(sydroads): sf_lines must be class "sf" and have highway and geometry columns
net1 <- weight_streetnet(sydroads, type_col = "type") # works?                              
net <- weight_streetnet (sydroads, wt_profile = wts,                                        
type_col = colnm, id_col = "osm_id")                                                        
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.0 (2018-04-23)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  tz       Europe/London               
#>  date     2018-06-08
#> Packages -----------------------------------------------------------------
#>  package     * version date       source                              
#>  assertthat    0.2.0   2017-04-11 cran (@0.2.0)                       
#>  backports     1.1.2   2017-12-13 CRAN (R 3.5.0)                      
#>  base        * 3.5.0   2018-04-23 local                               
#>  bindr         0.1.1   2018-03-13 cran (@0.1.1)                       
#>  bindrcpp      0.2.2   2018-03-29 cran (@0.2.2)                       
#>  class         7.3-14  2015-08-30 cran (@7.3-14)                      
#>  classInt      0.2-3   2018-04-16 cran (@0.2-3)                       
#>  cli           1.0.0   2017-11-05 cran (@1.0.0)                       
#>  compiler      3.5.0   2018-04-23 local                               
#>  crayon        1.3.4   2017-09-16 CRAN (R 3.5.0)                      
#>  curl          3.2     2018-03-28 cran (@3.2)                         
#>  datasets    * 3.5.0   2018-04-23 local                               
#>  DBI           1.0.0   2018-05-02 cran (@1.0.0)                       
#>  devtools      1.13.5  2018-02-18 CRAN (R 3.5.0)                      
#>  digest        0.6.15  2018-01-28 CRAN (R 3.5.0)                      
#>  dodgr       * 0.0.3   2017-10-30 CRAN (R 3.5.0)                      
#>  dplyr         0.7.5   2018-05-19 cran (@0.7.5)                       
#>  e1071         1.6-8   2017-02-02 cran (@1.6-8)                       
#>  evaluate      0.10    2016-10-11 CRAN (R 3.3.2)                      
#>  foreign       0.8-70  2018-04-23 CRAN (R 3.5.0)                      
#>  geosphere     1.5-7   2017-11-05 cran (@1.5-7)                       
#>  glue          1.2.0   2017-10-29 CRAN (R 3.5.0)                      
#>  graphics    * 3.5.0   2018-04-23 local                               
#>  grDevices   * 3.5.0   2018-04-23 local                               
#>  grid          3.5.0   2018-04-23 local                               
#>  htmltools     0.3.6   2017-04-28 CRAN (R 3.5.0)                      
#>  httr          1.3.1   2017-08-20 cran (@1.3.1)                       
#>  igraph        1.2.1   2018-03-10 cran (@1.2.1)                       
#>  jsonlite      1.5     2017-06-01 cran (@1.5)                         
#>  knitr         1.20    2018-02-20 CRAN (R 3.5.0)                      
#>  lattice       0.20-35 2017-03-25 CRAN (R 3.5.0)                      
#>  lubridate     1.7.4   2018-04-11 cran (@1.7.4)                       
#>  magrittr      1.5     2014-11-22 CRAN (R 3.3.2)                      
#>  maptools      0.9-2   2017-03-25 CRAN (R 3.5.0)                      
#>  memoise       1.1.0   2017-04-21 CRAN (R 3.5.0)                      
#>  methods     * 3.5.0   2018-04-23 local                               
#>  mime          0.5     2016-07-07 CRAN (R 3.5.0)                      
#>  openxlsx      4.1.0   2018-05-26 cran (@4.1.0)                       
#>  osmdata       0.0.7   2018-05-17 CRAN (R 3.5.0)                      
#>  pillar        1.2.3   2018-05-25 cran (@1.2.3)                       
#>  pkgconfig     2.0.1   2017-03-21 cran (@2.0.1)                       
#>  purrr         0.2.5   2018-05-29 cran (@0.2.5)                       
#>  R.methodsS3   1.7.1   2016-02-16 cran (@1.7.1)                       
#>  R.oo          1.22.0  2018-04-22 cran (@1.22.0)                      
#>  R.utils       2.6.0   2017-11-05 cran (@2.6.0)                       
#>  R6            2.2.2   2017-06-17 cran (@2.2.2)                       
#>  raster        2.6-7   2017-11-13 cran (@2.6-7)                       
#>  rbenchmark    1.0.0   2012-08-30 CRAN (R 3.5.0)                      
#>  Rcpp          0.12.17 2018-05-18 CRAN (R 3.5.0)                      
#>  rgdal         1.3-2   2018-06-08 CRAN (R 3.5.0)                      
#>  rgeos         0.3-27  2018-06-01 cran (@0.3-27)                      
#>  rlang         0.2.1   2018-05-30 cran (@0.2.1)                       
#>  rmarkdown     1.9     2018-03-01 CRAN (R 3.5.0)                      
#>  rprojroot     1.3-2   2018-01-03 CRAN (R 3.5.0)                      
#>  rvest         0.3.2   2016-06-17 CRAN (R 3.3.2)                      
#>  sf          * 0.6-3   2018-05-17 cran (@0.6-3)                       
#>  sp            1.3-1   2018-06-05 CRAN (R 3.5.0)                      
#>  spData        0.2.8.9 2018-06-03 Github (nowosad/spData@7b53933)     
#>  spDataLarge   0.2.6.5 2018-06-02 Github (nowosad/spDataLarge@bc058ad)
#>  stats       * 3.5.0   2018-04-23 local                               
#>  stplanr     * 0.2.5   2018-06-08 local                               
#>  stringi       1.2.2   2018-05-02 CRAN (R 3.5.0)                      
#>  stringr       1.3.1   2018-05-10 CRAN (R 3.5.0)                      
#>  tibble        1.4.2   2018-01-22 cran (@1.4.2)                       
#>  tidyselect    0.2.4   2018-02-26 cran (@0.2.4)                       
#>  tools         3.5.0   2018-04-23 local                               
#>  udunits2      0.13    2016-11-17 cran (@0.13)                        
#>  units         0.5-1   2018-01-08 cran (@0.5-1)                       
#>  utf8          1.1.4   2018-05-24 cran (@1.1.4)                       
#>  utils       * 3.5.0   2018-04-23 local                               
#>  withr         2.1.2   2018-03-15 CRAN (R 3.5.0)                      
#>  xml2          1.2.0   2018-01-24 CRAN (R 3.5.0)                      
#>  yaml          2.1.19  2018-05-01 CRAN (R 3.5.0)                      
#>  zip           1.0.0   2017-04-25 cran (@1.0.0)
```

</details>

**Comment by mpadge** [comment] 2018-06-08 19:47
Great failure demos from the master of breakage. Thanks!

**Comment by mpadge** [comment] 2018-06-11 09:48
First things first: I am aware of the first errors, but can't reproduce them. These both work for me
```
hampi
sf::st_sf(hampi)
```
The errors **used to**arise when `sf` was loaded after `dodgr`, but shouldn't do so anymore, and don't when I test it.

**Comment by mpadge** [comment] 2018-06-11 10:05
Most of these are due to out-of-date `dodgr`. You have
```
> si <- (devtools::session_info() [2])$packages
> si [si$package == "dodgr", ]
 package * version   date source
 dodgr   * 0.0.3   2017-10-30 CRAN (R 3.5.0)  
```

Most errors already fixed with
```
 package * version   date source
 dodgr   * 0.1.0.099 <NA> local
```
One unhelpful error nevertheless arises with
```
> devtools::load_all (".", export_all = FALSE)
Loading dodgr
> library(stplanr)
> library(sf)
Linking to GEOS 3.6.2, GDAL 2.2.4, proj.4 4.9.3
> data_dir <- system.file("extdata", package = "stplanr")
> unzip(file.path(data_dir, "sydroads.zip"), exdir = tempdir())
> sydroads <- read_sf(tempdir(), "roads")
> colnm <- "type"
> road_types <- unique (sydroads[[colnm]])
> wts <- rep(1, length(road_types))
> names (wts) <- road_types
> weight_streetnet(sydroads)
Error in rcpp_sf_as_network(sf_lines, pr = wt_profile) : 
  CHAR() can only be applied to a 'CHARSXP', not a 'NULL'
```
The error is fair enough, because `weight_streetnet` does not know which column to use for the weights, but the error is entirely uninformative, so I shall fix ...

**Closed** 2018-06-11 10:11 UTC

**Comment by mpadge** [comment] 2018-06-11 10:13
That push gives:
```
> weight_streetnet(sydroads)
Error in weight_streetnet(sydroads) : 
  Please specify type_col to be used for weighting streetnet                                                                            
```
A similiar one also implmented for unspecified `id_col`.

**Comment by Robinlovelace** [comment] 2018-06-11 10:17
Sounds good - many thanks for the quick fix. Was a good learning experience generating those error messages and playing with **dodgr**. I'm definitely getting up-to-speed with it now! 2 questions:

1. When are you planning on updating the [CRAN version](https://cran.r-project.org/web/packages/dodgr/)?
2. Do you think it would be good to add a **dodgr** example here:  http://geocompr.robinlovelace.net/transport.html#route-networks ? thinking of updating the example to run on a bigger road network, e.g. `dodgr_streetnet("Bristol")`

**Comment by mpadge** [comment] 2018-06-11 10:32
I should get the CRAN version in, coz it looks like v0.1 is ready to go ([here](https://github.com/ATFutures/dodgr/projects/1)). I needed `osmdata` update first, which is done, but then haven't found time to update `dodgr`. Thanks for the prompt - I'll do it pronto.

As for your 2nd Q: Of course I think it would be a good idea - it would serve my own selfish interests. You could easily squeeze in a `dodgr_flows_aggregate()` to show how to extend beyond betweenness centrality (implicit homogeneous flow matrix of 1) to use actual (heterogeneous) OD matrices?

**Comment by Robinlovelace** [comment] 2018-06-11 10:35
Yes that input would be greatly beneficial to readers IMO and help get the `dodgr` word out there!
