### ISSUE TITLE
Function to compute travel time

### ISSUE THREAD

**Issue by fzenoni** [ATFutures/dodgr#76] opened 2018-11-22 09:18 UTC
After [our previous discussion ](https://github.com/ropensci/osmdata/issues/156) I started making comparisons between `dodgr` and OSRM. And I have to say that this package is most impressive and shows an amazing potential.

However, being more interested in travel time than distance, is there a function similar to `dodgr_dists` that could take care of this? I couldn't find it myself. If it doesn't exist, would it be a good plan for an enhancement?

**Comment by mpadge** [comment] 2018-11-22 10:19
That's great to hear! I'd love it if you could devise and structured and reproducible benchmark of `dodgr` and OSRM. Even better if you could PR straight into the [`benchmark` vignette](https://github.com/ATFutures/dodgr/blob/master/vignettes/benchmark.Rmd) (with rendered version [here](https://atfutures.github.io/dodgr/articles/benchmark.html)). Let me know if you'd be interested in doing that.

As for your question ... this time a more affirmative answer. There is no such function at the moment, but there definitely should and will be, also as part of #59. The basic infrastructure is all there, because it's primarily just a linear conversion, **BUT** the missing bit is traffic lights, which are part of the more general issue that `dodgr` can not route using nodal properties. It currently only uses edge properties (as weighted distances). Incorporating nodal properties in routing calculations is very straightforward, I just have to implement it. This issue can serve to get that done, and I've already put it in the [project board](https://github.com/ATFutures/dodgr/projects/1), so it should be implemented fairly soon.

**Comment by mpadge** [comment] 2018-11-22 10:30
Some useful insights on google travel times [here](https://www.betterbybicycle.com/2014/09/how-accurate-are-google-maps-cycling.html)

**Comment by fzenoni** [comment] 2018-11-22 12:19
>  Let me know if you'd be interested in doing that.

It sounds like a great proposal. I am currently on project and I can't commit on extra tasks, but I will certainly let you know if things evolve.

**Comment by fzenoni** [comment] 2018-11-23 15:09
In conclusion it looks like `dodgr` is currently focusing on providing the shortest route, not the fastest. In comparison, OSRM offers some flexibility in that respect (but not during query-time, currently one needs to recompile the map, see https://github.com/Project-OSRM/osrm-backend/issues/4007).

In the studies I made, fastest route is more interesting, especially for motorized vehicles that suffer of accessibility penalties.

I will nevertheless keep a close watch on `dodgr`, and I'm looking forward to the next steps.

**Comment by mpadge** [comment] 2019-03-27 08:12
Time-based routing started as demonstrated in #72. Two remaining aspects:

- [ ] Wait times at traffic lights
- [ ] Turn angles

Those are now relatively straightforward and will be implemented soon.

**Comment by mpadge** [comment] 2019-03-27 08:14
And actually closing here and moving to duplicate at #88

**Closed by mpadge** 2019-03-27 08:14 UTC
